-- 1. URL Scans Table
CREATE TABLE IF NOT EXISTS url_scans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT NOT NULL,
    risk_score INTEGER NOT NULL,
    evidence JSONB,
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Malicious Patterns (Self-Learning Knowledge Base)
CREATE TABLE IF NOT EXISTS malicious_patterns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern TEXT NOT NULL,
    type TEXT NOT NULL, -- 'keyword', 'tld', 'structure', 'redirect'
    evidence JSONB,
    risk_weight INTEGER DEFAULT 50,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Safe Patterns (Allowlist Learning)
CREATE TABLE IF NOT EXISTS safe_patterns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern TEXT NOT NULL,
    evidence JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Download Threats (File Intelligence)
CREATE TABLE IF NOT EXISTS download_threats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name TEXT,
    extension TEXT,
    probability INTEGER, -- 0-100
    source_domain TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Behavior Signatures (AI extracted features)
CREATE TABLE IF NOT EXISTS behavior_signatures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    features_json JSONB NOT NULL,
    risk_weight INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Redirect Graphs (Tracking complex redirect chains)
CREATE TABLE IF NOT EXISTS redirect_graphs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain TEXT NOT NULL,
    redirects_json JSONB NOT NULL, -- Array of hops
    risk_weight INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. File Reports (Full Scan Logs)
CREATE TABLE IF NOT EXISTS file_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_hash TEXT,
    filename TEXT,
    size INTEGER,
    result_json JSONB,
    risk_score INTEGER,
    reasons JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_url_scans_url ON url_scans(url);
CREATE INDEX IF NOT EXISTS idx_malicious_patterns_pattern ON malicious_patterns(pattern);
CREATE INDEX IF NOT EXISTS idx_download_threats_source ON download_threats(source_domain);
CREATE INDEX IF NOT EXISTS idx_file_reports_hash ON file_reports(file_hash);
